name: Run all tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install cc65
      run: sudo apt-get install cc65

    - name: Assemble kizapr-u102.bin
      run: cd kizapr-u102 && make && cat kizapr-u102.lst
