name: Run all tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install cc65
      run: sudo apt-get install cc65

    - name: Assemble kizapr-u102.bin
      run: cd kizapr-u102 && make && cat kizapr-u102.lst

    - name: 'Upload build artifacts'
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
            kizapr-u102/kizapr-u102.bin
            kizapr-u102/kizapr-u102.lst
